export const GET_USER = 'GET_USER';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_OFFERS = 'GET_PRODUCTS_OFFERS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_TOP_SHOPS = 'GET_TOP_SHOPS';
