export const GET_ADMIN = 'GET_ADMIN';
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const GET_DISCOUNT_CODES = 'GET_DISCOUNT_CODES';
export const GET_ADMIN_PRODUCTS = 'GET_ADMIN_PRODUCTS';
export const GET_ADMIN_PRODUCT_EVENTS = 'GET_ADMIN_PRODUCT_EVENTS';

export const GET_ADMIN_ORDERS = 'GET_ADMIN_ORDERS';
export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
