export const GET_SELLER = 'GET_SELLER';
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const GET_DISCOUNT_CODES = 'GET_DISCOUNT_CODES';
export const GET_SHOP_PRODUCTS = 'GET_SHOP_PRODUCTS';

export const GET_SELLER_ORDERS = 'GET_SELLER_ORDERS';
export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
